config/routes.rb
Rails.application.routes.draw do
  get 'searchs/search'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books do
    resource :favorites,only:[:create,:destroy]
    resources :book_comments,only:[:create,:destroy]
  end
  resources :users,only:[:index,:show,:edit,:update] do
    resource :relationships,only:[:create,:destroy]
    get 'followings' => 'relationships#followings',as:'followings'
    get 'followers' => 'relationships#followers',as:'followers'
  end

  get '/search', to: 'searchs#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence:true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name:"User"
  belongs_to :followed, class_name:"User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reverse_of_relationships,class_name:"Relationship",foreign_key:"followed_id",dependent: :destroy
  has_many :relationships,class_name:"Relationship",foreign_key:"follower_id",dependent: :destroy
  has_many :followers,through: :reverse_of_relationships,source: :follower
  has_many :followings,through: :relationships,source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end


  validates :name, presence: true, length: { minimum: 2 ,maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
   @book = Book.find(params[:book_id])
   @book_comment = BookComment.new(book_comment_params)
   @book_comment.book_id = @book.id
   @book_comment.user_id = current_user.id
   if @book_comment.save
     redirect_to book_path(@book.id)
   else
     render 'books/show'
   end
  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
    book_comment.destroy
    redirect_to request.referer
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  #before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def new
    @book = Book.new

  end

  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      redirect_to book_path(@book_new.id),notice:'You have created book successfully.'
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @book_new = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id),notice:'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book =Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  # def ensure_correct_user(book)
  #   if book.user.id != current_user.id
  #     redirect_to book_path(book.id)
  #   end
  # end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif search == "forward_match"
        User.where("name LIKE?",content+'%')
      elsif search == "backward_match"
        User.where("name LIKE?",'%'+content)
      else
        User.where("name LIKE ?", '%'+content+'%')
      end
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      elsif search == "forward_match"
        Book.where("title LIKE?",content+'%' )
      elsif search == "backward_match"
        Book.where("title LIKE?",'%'+content)
      else
        Book.where("title LIKE?",'%'+content+'%')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  

  def index
    @users = User.all
    @user = current_user
    @book_new = Book.new


  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new =  Book.new
  end

  def edit
    @user=User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id),notice:'You have updated user successfully.'
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
  <% books.each do |book| %>
    <tr>
      <td>
        <%= attachment_image_tag book.user,:profile_image,fallback: "no.image.png",size: "40x40" %>
      </td>
      <td><%= link_to book.title, book_path(book) %></td>
      <td><%= book.body %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
       <%= @book.errors.count %>件のerrorが発生しました
       <% @book.errors.full_messages.each do |message| %>
         <%= message %>
       <% end %>
      <% end %>
      <%=form_with model:@book, local:true do |f|%>
      <h4>Title</h4>
      <%=f.text_field:title%>
      <h4>Opinion</h4>
      <%=f.text_area:body%>
      <%=f.submit "Update Book"%>
      <%= link_to "Show" ,book_path %>
       |
      <a class="back" href="/books">Back</a>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
 <div class="row">
  <%= render 'users/info',user:@user,book:@book_new %>
  <div class="col-md-8 offset-md-1">
    <h2>Book</h2>

    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%=link_to user_path(book.user.id) do%>
            　<%=attachment_image_tag book.user, :profile_image%>
            <%end%>
          </td>
          <td>
            <%=link_to book.title, book_path(book.id) %>
          </td>
          <td>
             <%=book.body%>

          </td>
          <td>
              <% if book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(book), method: :delete do %>
                 ♥<%= book.favorites.count %>いいね
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to book_favorites_path(book), method: :post do %>
                 ♡<%= book.favorites.count %> いいね
                <% end %>
              </p>
              <% end %>
          </td>
          <td>
            <p>コメント件数:<%= book.book_comments.count %></p>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
 </div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
   <%= render 'users/info',user:@user, book:@book_new%>
   <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
     <tbody>
      <tr>
        <td>
          <%=link_to user_path(@user.id) do%>
           <%=attachment_image_tag @user, :profile_image,fallback: "no.image.png",size: "40x40"%>
           <%=@user.name%>
          <%end%>
        </td>
        <td>
          <%=link_to @book.title, book_path(@book.id) %>
        </td>
        <td>
            <%=@book.body%>
        </td>
        <td>
         <% if @book.favorited_by?(current_user) %>
          <p>
          <%= link_to book_favorites_path(@book), method: :delete do %>
            ♥<%= @book.favorites.count %>いいね
          <% end %>
          </p>
          <% else %>
          <p>
          <%= link_to book_favorites_path(@book), method: :post do %>
            ♡<%= @book.favorites.count %> いいね
          <% end %>
          </p>
         <% end %>
        </td>
        <td>
          <p>コメント件数:<%= @book.book_comments.count %></p>
        </td>
        <% if @user.id == current_user.id %>
         <td><%=link_to "Edit", edit_book_path(@book.id)%></td>
         <td><%=link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？"%></td>
        <%end%>
      </tr>
     </tbody>
    </table>
    <div>
      <% @book.book_comments.each do |book_comment| %>
       <%= book_comment.user.name %>
       <%= book_comment.comment %>
       <% if @user.id == current_user.id %>
        <%= link_to "Destroy", book_book_comment_path(@book, book_comment), method: :delete, "data-confirm" => "本当に消しますか？"%>
       <% end %>
      <% end %>
    </div>
    <div>
     <%= form_with(model:[@book,@book_comment] , local: true) do |f| %>
      <%= f.text_area :comment ,size:"90x5" %>
      <%= f.submit'送信' %>
     <% end %>
    </div>
   </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      !
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<div class ="container">
  <div class ="row">
    <div  class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcom to
        <i class= "fas fa-book">
        </i>
        <strong>Bookers</strong>
        !!
      </h1>
      <p>
        In
        <i class="fas fa-book">
        </i>
        <strong>Bookers</strong>
        ,
      </p>
      <p>you can share and exchange your opinions, inpressions, and emotions</p>
      <p>about various books!</p>
      <div class= "btn-wrapper col-10 mx-auto">
        <div class="row">
          <!--< class="btn btn-info btn-sm btn-block mb-3 sign_in"　href="/users/sign_in">Log in</a>-->
          <%= link_to "Log in", new_user_session_path,  class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <a class ="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/followers.html.erb
<h2>Follow Users</h2>
<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th colspan ="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
        <%= attachment_image_tag user, :profile_image, fallback:"no.image.png", size:"40x40" %>
      </td>
      <td><%= user.name %></td>
      <td>フォロー数:<%= user.followings.count %></td>
      <td> フォロワー数:<%= user.followers.count %></td>
      <td><%= link_to'show',user_path(user.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th colspan ="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
        <%= attachment_image_tag user, :profile_image, fallback:"no.image.png", size:"40x40" %>
      </td>
      <td><%= user.name %></td>
      <td>フォロー数:<%= user.followings.count %></td>
      <td> フォロワー数:<%= user.followers.count %></td>
      <td><%= link_to'show',user_path(user.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/searchs/_form.html.erb
<% if user_signed_in? %>
 <%= form_tag(search_path,method: :get) do %>
  <%= text_field_tag 'content' %>
  <%= select_tag 'model',options_for_select({"User" => "user", "Book" => "book"}) %>
  <%= select_tag 'method', options_for_select({"完全一致" => "perfect","部分一致" => "partial_math","前方一致" => "forward_math","後方一致" => "backward_mach"}) %>
  <%= submit_tag '検索' %>
 <% end %>
<% end %>

app/views/searchs/search.html.erb
<% if @model =='user' %>
 <h2>Users search for <%= @content %></h2>
 <%= render 'users/index',users:@records %>
<% else @model =='book' %>
 <h2>Books search for <%= @content %></h2>
 <%= render 'books/index',books:@records %>
<% end %>

app/views/users/_index.html.erb
<% users.each do |user| %>
 <%= link_to user_path(user) do %>
  <%= user.name %>
 <% end %>
<% end %>

app/views/users/_info.html.erb
       <div class = "col-md-3">
           <%= flash[:notice] %>
            <h2>User info</h2>
            <%= attachment_image_tag user, :profile_image, :fill,100,100,fallback:"no.image.png",size:"100x100" %>
            <table class="table">
                <tbody>
                    <tr></tr>
                    <tr>
                      <th>name</th>
                      <th><%= user.name%></th>
                    </tr>
                    <tr>
                      <th>introduction</th>
                      <th><%= user.introduction%></th>
                    </tr>
                    <tr>
                      <th>フォロー数:</th>
                      <th><%= link_to user.followings.count ,user_followings_path(user.id)  %></th>
                    </tr>
                    <tr>
                      <th>フォロワー数:</th>
                      <th><%= link_to user.followers.count ,user_followers_path(user.id) %></th>
                    </tr>
                </tbody>
            </table>
            <div>
              <% unless current_user == user %>
              <% if current_user.following?(user.id) %>
               <%=link_to"フォローを外す",user_relationships_path(user.id) ,method: :delete,class:"btn brn-primary"%>
              <% else %>
               <%=link_to"フォローする",user_relationships_path(user.id) ,method: :post,class:"btn btn-success"%>
              <% end %>
              <% end %>
            </div>
            <div class="row">
                <%= link_to "", edit_user_path(user), class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user_path" %>
            </div>
            <h2>New book</h2>
            <% if book.errors.any? %>
             <%= book.errors.count %>件のerrorが発生しました
             <% book.errors.full_messages.each do |message| %>
               <%= message %>
             <% end %>
            <% end %>
            <%= form_with model: book, local:true do |f| %>
             <h4>Title</h4>
             <%=f.text_field:title%>
             <h4>Opinion</h4>
             <%=f.text_area:body%>
             <%=f.submit"Create Book" %>
            <% end %>
        </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
       <%= @user.errors.count %>件のエラーが発生しました
       <% @user.errors.full_messages.each do |message| %>
         <%= message %>
        <% end %>
      <% end %>
      <%=form_with model:@user,local:true do |f|%>
      <p>Name</p>
      <%=f.text_field:name%>
      <p>Image</p>
      <%=f.attachment_field :profile_image%>
      <p>Introduction</p>
      <%=f.text_area:introduction%>
      <%=f.submit "Update User" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render "users/info",user:@user, book:@book_new %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%=attachment_image_tag user, :profile_image,fallback: "no.image.png",size: "40x40"%>
            </td>
            <td>
              <%=user.name%>
            </td>
            <td>フォロー数:<%= user.followings.count %></td>
            <td> フォロワー数:<%= user.followers.count %></td>
            <td>
              <% unless current_user == user %>
              <% if current_user.following?(user) %>
               <%=link_to"フォローを外す",user_relationships_path(user.id) ,method: :delete,class:"btn brn-primary"%>
              <% else %>
               <%=link_to"フォローする",user_relationships_path(user.id) ,method: :post,class:"btn btn-success"%>
              <% end %>
              <% end %>

            </td>
            <td>
              <%=link_to "Show", user_path(user.id), class:"btn btn-danger" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render "info",user:@user, book:@book_new %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%=link_to user_path(@user.id) do%>
               <%=attachment_image_tag @user, :profile_image,fallback: "no.image.png",size: "40x40"%>
              <%end%>
            </td>
            <td>
              <%=link_to book.title, book_path(book.id) %>
            </td>
            <td>
              <%=book.body%>
            </td>
            <td>
              <% if book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(book), method: :delete do %>
                 ♥<%= book.favorites.count %>いいね
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to book_favorites_path(book), method: :post do %>
                 ♡<%= book.favorites.count %> いいね
                <% end %>
              </p>
              <% end %>
            </td>
            <td>
              <p>コメント件数:<%= book.book_comments.count %></p>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>